gerrit_server = "review.gerrithub.io"
project_root = "/home/rahul/app/orion/"
repo = "Bit2trades/orion"
remote_name = "origin"

events = [
  "change-abandoned",
  "change-deleted",
  "change-merged",
  "change-restored",
  "dropped-output",
  "patchset-created",
  "ref-updated",
  "batch-ref-updated",
  # "reviewer-added",
  # "reviewer-deleted",
  # "topic-changed",
  # "wip-state-changed",
  # "private-state-changed",
  # "vote-deleted",
]
