#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[gerrit]
default-remote-branch = "main"

[revsets]
log = 'gerrit_normal'

[revset-aliases]
gerrit_all = 'fork_point(all() ~ ::main@origin | main@origin |tags())::'

gerrit_normal = 'fork_point((all() ~ ::main@origin | main@origin |tags())):: ~ tags("hidden/*")'

gerrit_hidden = 'tags("hidden/*")| main@origin'
